services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    volumes:
      - /home/ec2-user/mnt/srv:/srv
      - ./filebrowser:/database
      - ./filebrowser:/config
    ports:
      - "8081:80"

  app:
    image: photo-slider:latest
    environment:
      - AWS_REGION=eu-north-1
      - AWS_DEFAULT_REGION=eu-north-1
      - BUCKET_NAME=ickovics-home
      - FETCH_INTERVAL=60
      - DISPLAY_TIME=10
    ports:
    - "8080:8080"

  nginx:
    image: arm64v8/nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - filebrowser
