services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    volumes:
      - /home/ec2-user/mnt/srv:/srv
      - /home/ec2-user/mnt/srv/photo-slider-storage/_internal/database.db:/database.db
    environment:
      - PUID=1000
      - PGID=1000

    ports:
      - "8081:80"

  app:
    image: photo-slider:latest
    environment:
      - AWS_REGION=eu-north-1
      - AWS_DEFAULT_REGION=eu-north-1
      - BUCKET_NAME=photo-slider-storage
      - FETCH_INTERVAL=60
      - DISPLAY_TIME=10
    ports:
    - "8080:8080"

  nginx:
    image: arm64v8/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - app
      - filebrowser
