services:
  filestash:
    image: machines/filestash:latest
    environment:
      - APPLICATION_URL=upload.loopslide.xyz
      - CANARY=false
      - AWS_REGION=eu-north-1
      - AWS_DEFAULT_REGION=eu-north-1
    ports:
      - "8334:8334"
    volumes:
      - filestash:/app/data/state/

  app:
    image: photo-slider:latest
    environment:
      - AWS_REGION=eu-north-1
      - AWS_DEFAULT_REGION=eu-north-1
      - BUCKET_NAME=ickovics-home
      - FETCH_INTERVAL=60
      - DISPLAY_TIME=10
    build:
      context: .
    ports:
    - "8080:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - filestash

volumes:
  filestash: {}
